import { Inter } from 'next/font/google';
import { CircleAlert, CircleCheck, Info, TriangleAlert } from 'lucide-react';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from 'sonner';

import type { Metadata } from 'next';
import RootProviders from './providers';

import './globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} antialiased`} suppressHydrationWarning>
      <body className="min-h-[100dvh]">
        <NuqsAdapter>
          <RootProviders>{children}</RootProviders>
        </NuqsAdapter>

        <Toaster
          closeButton
          position="bottom-center"
          className="pointer-events-auto"
          icons={{
            error: <CircleAlert className="size-5 text-red-500" />,
            success: <CircleCheck className="size-5 text-emerald-500" />,
            info: <Info className="size-5 text-blue-500" />,
            warning: <TriangleAlert className="size-5 text-amber-500" />
          }}
        />
      </body>
    </html>
  );
}
